//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fdelete.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("fdelete.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .EXTRAHOTELERO HOSPEDAJE
        ///.T.
        ///.php
        ///.,
        ///.-
        ///.-0.html
        ///.-110,-maria-lund-45906.-511-gl.php
        ///.-bouncing
        ///.-safety-fear
        ///.-tillagg-order-85497.php
        ///.0
        ///.0--DUP.htm
        ///.0-0-0.html
        ///.0-2.html
        ///.0-4.html
        ///.0-features-print.htm
        ///.0-pl1
        ///.0-rc1
        ///.0-to-1.2.php
        ///.0-to1.2.php
        ///.0.0
        ///.0.0.0
        ///.0.1
        ///.0.1.1
        ///.0.10
        ///.0.10.html
        ///.0.11
        ///.0.11-pr1
        ///.0.15
        ///.0.2
        ///.0.3
        ///.0.328.1.php
        ///.0.329.1.php
        ///.0.330.1.php
        ///.0.35
        ///.0.4
        ///.0.5
        ///.0.6
        ///.0.7
        ///.0.8
        ///.0.8.html
        ///.0.806.1.php
        ///.0.html
        ///.0.jpg
        ///.0.pdf
        ///.0.xml
        ///.0.zip
        ///.00
        ///.00.8169
        ///.0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string allExtensions {
            get {
                return ResourceManager.GetString("allExtensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///.
        /// </summary>
        internal static string dirLBData {
            get {
                return ResourceManager.GetString("dirLBData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///.
        /// </summary>
        internal static string extLBData {
            get {
                return ResourceManager.GetString("extLBData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\
        ///C:\Windows
        ///C:\Windows\System32
        ///C:\Program Files
        ///C:\Program Files (x86)
        ///C:\Users
        ///C:\Users\Default
        ///C:\Users\Public
        ///C:\Windows\Temp
        ///C:\Windows\System32\config
        ///C:\Windows\Winsxs
        ///C:\Windows\Boot
        ///C:\Windows\SoftwareDistribution
        ///C:\Windows\Installer
        ///C:\Windows\System32\drivers
        ///C:\ProgramData
        ///C:\Recovery
        ///.
        /// </summary>
        internal static string invalidDirData {
            get {
                return ResourceManager.GetString("invalidDirData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string invalidFileData {
            get {
                return ResourceManager.GetString("invalidFileData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True
        ///True
        ///True
        ///True
        ///.
        /// </summary>
        internal static string settingsData {
            get {
                return ResourceManager.GetString("settingsData", resourceCulture);
            }
        }
    }
}
